singularity: "docker://continuumio/miniconda3:latest"

rule all:
    input:
        "ls_dir.txt",
        "../output/snakemake_generated_output.txt"

rule ls_dir:
    output: "ls_dir.txt"
    shell: """
    printf "Working Dir: " > {output[0]}
    readlink -f . >> {output[0]}
    ls -lh >> {output[0]}
    printf "\n\n" >> {output[0]}
    printf "Parent Dir: " >> {output[0]}
    readlink -f ../ >> {output[0]}
    ls -lh ../>> {output[0]}
    printf "\n\n" >> {output[0]}
    printf "Local Scratch: " >> {output[0]}
    echo "/lscratch" >> {output[0]}
    ls -lh /lscratch >> {output[0]}
    printf "\n\n" >> {output[0]}
    echo "root: /" >> {output[0]}
    ls -Cw 80 /  >> {output[0]}
    printf "\n\n" >> {output[0]}
    echo "df -h" >> {output[0]}
    df -ah >> {output[0]}
    """

rule touch_outside:
    input: "../output/file_A.txt"
    output: "../output/snakemake_generated_output.txt"
    shell: """
    cat {input[0]} > {output[0]}
    """
