singularity: "docker://continuumio/miniconda3:latest"

rule all:
    input: 
        "ls_dir.txt"
        "../output/snakemake_generated_output.txt"

rule ls_dir:
    output: "../ls_dir.txt"
    shell: """
    echo "Working Dir" > {output[0]}
    pwd >> {output[0]}
    ls -lh >> {output[0]}
    echo "Parent Dir" >> {output[0]}
    ls -lh ../>> {output[0]}
    echo "/lscratch" >> {output[0]}
    ls -lh /lscratch >> {output[0]}
    """

rule touch_outside:
    input: "../output/file_A.txt"
    output: "../output/snakemake_generated_output.txt"
    shell: """
    cat {input[0]} > {output[0]}
    """
